In [11]:
import numpy as np


freq1 = np.fft.fftfreq(11,1/11);

Freq= np.arange(10);
ux = np.sin(2*np.pi*Freq/3);

uxk= np.fft.fftshift(np.fft.fft(ux));

ux_ = np.fft.ifft(np.fft.fftshift(uxk));
ux_ = np.real(ux_)
freq2 = np.fft.fftshift(freq1)
freq3 = np.fft.ifftshift(freq1);
print("#################")
print(f"{freq1}");
print(f"{freq2}");
print(f"{freq3}");
print("################")
print(ux);
print(ux_);

a  = np.arange(0,9);
a_ = np.fft.fftshift(a)

print(a," ",a_," ",_a)

#################
[ 0.  1.  2.  3.  4.  5. -5. -4. -3. -2. -1.]
[-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
[ 5. -5. -4. -3. -2. -1.  0.  1.  2.  3.  4.]
################
[ 0.00000000e+00  8.66025404e-01 -8.66025404e-01 -2.44929360e-16
  8.66025404e-01 -8.66025404e-01 -4.89858720e-16  8.66025404e-01
 -8.66025404e-01 -7.34788079e-16]
[-1.77635684e-16  8.66025404e-01 -8.66025404e-01 -2.22044605e-16
  8.66025404e-01 -8.66025404e-01 -3.55271368e-16  8.66025404e-01
 -8.66025404e-01 -6.66133815e-16]
[0 1 2 3 4 5 6 7 8]   [5 6 7 8 0 1 2 3 4]   [0 1 2 3 4 5 6 7 8]
